"""Add report columns

Revision ID: 3738c30fe392
Revises: 1e4cc5614d3b
Create Date: 2025-11-23 18:16:40.189005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3738c30fe392'
down_revision = '1e4cc5614d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('disposal_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('disposal_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('disposal_reason')
        batch_op.drop_column('disposal_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
