"""Added DisposalHistory table

Revision ID: 9366af4502de
Revises: c865b7e671ed
Create Date: 2025-11-24 13:02:39.891842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9366af4502de'
down_revision = 'c865b7e671ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('resolution_date')
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolution_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolution_date', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
