"""Added resolution columns to Inventory

Revision ID: c865b7e671ed
Revises: 3738c30fe392
Create Date: 2025-11-23 23:48:00.311337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c865b7e671ed'
down_revision = '3738c30fe392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resolution_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolution_date')
        batch_op.drop_column('resolution_type')

    # ### end Alembic commands ###
