"""remove unique constraint from item_description

Revision ID: cba1e127601f
Revises: 9366af4502de
Create Date: 2025-12-06 09:53:31.253210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba1e127601f'
down_revision = '9366af4502de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        # 1. Update column length (kept from auto-generation)
        batch_op.alter_column('item_description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        
        # 2. MANUALLY ADDED: Remove the unique constraint
        # 'inventory_item_description_key' is the standard name PostgreSQL gives unique constraints.
        batch_op.drop_constraint('THE_ACTUAL_NAME_HERE', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        # Restore the unique constraint
        batch_op.create_unique_constraint('inventory_item_description_key', ['item_description'])

        # Restore the column length
        batch_op.alter_column('item_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###